apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/miguelruizdev/ttc-connectors-reward:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/miguelruizdev/ttc-connectors-reward:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: ttc-connectors-reward
        chartPath: charts/ttc-connectors-reward
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/miguelruizdev/ttc-connectors-reward"
          image.tag: "{{.TAG}}"
